server:
  port: 8081

spring:
  application:
    name: football-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

football:
  api:
    url: https://api.football-data.org/v4
    key: 29281135cd014b44a755962e198043d2

