version: '3'
services:
  eureka-server:
    image: eureka-server:latest  # Używamy już zbudowanego obrazu
    ports:
      - "8761:8761"
    networks:
      - gateway-network
    restart: always  # Opcjonalnie

  gateway:
    image: api-gateway:latest  # Używamy już zbudowanego obrazu
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - gateway-network
    restart: always  # Opcjonalnie

  bundesliga-api:
    image: bundesliga-api  # Obraz dla bundesliga-api
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - gateway-network
    restart: always  # Opcjonalnie

  laliga-api:
    image: laliga-api  # Obraz dla laliga-api
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - gateway-network
    restart: always  # Opcjonalnie

  premierleague-api:
    image: premierleague-api  # Obraz dla premierleague-api
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - gateway-network
    restart: always  # Opcjonalnie

  ekstraklasa-api:
    image: ekstraklasa-api  # Obraz dla ekstraklasa-api
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - gateway-network
    restart: always  # Opcjonalnie

  seriea-api:
    image: seriea-api  # Obraz dla seriea-api
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - gateway-network
    restart: always  # Opcjonalnie

  transfermarket:
    image: transfermarket  # Obraz dla transfermarket
    ports:
      - "8086:8086"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - gateway-network
    restart: always  # Opcjonalnie

networks:
  gateway-network:
    driver: bridge


