server:
  port: 8080
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: football-service
          uri: lb://football-service
          predicates:
            - Path=/football/**
