server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: laliga-api
          uri: http://localhost:8081
          predicates:
            - Path=/laliga/**
        - id: bundesliga-api
          uri: http://localhost:8082
          predicates:
            - Path=/bundesliga/**
        - id: premierleague-api
          uri: http://localhost:8083
          predicates:
            - Path=/premierleague/**
        - id: ekstraklasa-api
          uri: http://localhost:8084
          predicates:
            - Path=/ekstraklasa/**
        - id: seriea-api
          uri: http://localhost:8085
          predicates:
            - Path=/seriea/**
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
