server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: laliga-api
          uri: http://localhost:8081
          predicates:
            - Path=/laliga/**
        - id: bundesliga-api
          uri: http://localhost:8082
          predicates:
            - Path=/bundesliga/**
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
