server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: laliga-api
          uri: lb://laliga-api  # Użycie load balancera Eureka
          predicates:
            - Path=/laliga/**
        - id: bundesliga-api
          uri: lb://bundesliga-api
          predicates:
            - Path=/bundesliga/**
        - id: premierleague-api
          uri: lb://premierleague-api
          predicates:
            - Path=/premierleague/**
        - id: ekstraklasa-api
          uri: lb://ekstraklasa-api
          predicates:
            - Path=/ekstraklasa/**
        - id: seriea-api
          uri: lb://seriea-api
          predicates:
            - Path=/seriea/**
        - id: transfermarket
          uri: lb://transfermarket
          predicates:
            - Path=/transfermarket/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

app:
  name: Api-gateway
  version: 1.0.0
  owner: Kacper Szabat
