server:
  port: 8084
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://eureka-server:8761/eureka/eureka/

spring:
  application:
    name: ekstraklasa-api
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/ekstraklasa
    username: ${DB_FOOTBALL_USERNAME}
    password: ${DB_FOOTBALL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false

app:
  name: Ekstraklasa-api
  version: 1.0.0
  owner: Kacper Szabat