server:
  port: 8083
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: premierleague-api
  datasource:
    url: jdbc:mysql://localhost:3306/premierleague
    username: Football
    password: Footballapi123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
