server:
  port: 8761
  address: 0.0.0.0
  servlet:
    context-path: /eureka


spring:
  application:
    name: eureka-server

  cloud:
    discovery:
      enabled: true
    loadbalancer:
      cache:
        type: caffeine

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 30000
    response-cache-update-interval-ms: 30000
    registry-sync-retries: 5
  instance:
    hostname: eureka-server
    prefer-ip-address: true

app:
  name: Eureka-server
  version: 1.0.0
  owner: Kacper Szabat