server:
  port: 8085
  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: seriea-api
  datasource:
    url: jdbc:mysql://localhost:3306/seriea
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
