server:
  port: 8081
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: laliga-api
  datasource:
    url: jdbc:mysql://localhost:3306/laliga
    username: Football
    password: Footballapi123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always